alias p="cd ~/src/www/projekty"
alias fl="cd ~/src/framelogic"
alias vpn-tauron="snx -s 193.28.0.100 -u x-pwasilewski"
alias vpn-tauron-close="snx -d"
alias tinker="php artisan tinker"
alias gl="git log --graph --oneline --decorate --all"
alias gvar="~/dotfiles/zsh/plugins/gvar/libexec/gvar.sh"
alias minio="~/Applications/minio server --address ":9191" ~/tmp/minio-data"
